
spring:
  data:
    mongodb:
      host: ${MONGODB_HOST:127.0.0.1}
      port: ${MONGODB_PORT:27017}
      username: ${MONGODB_USER:username}
      password: ${MONGODB_PASSWORD:password}
      database: ${MONGODB_DATABASE:test-debug-app}
      authentication-database: ${MONGODB_AUTHENTICATION_DATABASE:admin}

server:
  port: ${SERVER_PORT:8000}
management:
  server:
    port: ${MANAGEMENT_PORT:9000}
    endpoints.web.exposure.include: env,health,info
    endpoint.health.show-details: ALWAYS
