
spring:
  data:
    mongodb:
      host: 127.0.0.1
      port: 27017
      username: username
      password: password
      database: test-debug-app
      authentication-database: admin

server:
  port: 8081
